enum LocalStorageKeys {
    SELECTED_GUILD_ID = "SELECTED_GUILD_ID",
    GUILD_SETTINGS = "GUILD_SETTINGS",
    CHANNELS = "CHANNELS",
    GUILDS = "DISCORD_GUILDS",
    LOCAL_FORM_DATA = "LOCAL_FORM_DATA"
}

export default LocalStorageKeys;
