# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
name: Production
on:
  push:
    branches: ["main"]

jobs:
  checking-project:
    runs-on: ubuntu-latest

    steps:
      - name: "Get project ${{ github.event.repository.name }}"
        uses: actions/checkout@v3

      - name: Uses Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: "Install Dependencies"
        run: yarn

      - name: "Check Lint"
        run: yarn lint

      - name: "Build Project"
        run: yarn build

  build:
    needs: checking-project
    runs-on: ubuntu-latest
    steps:
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DOMAIN }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHPRIVATEKEY }}
          script: | 
            export PROJECT_NAME="${{ github.event.repository.name }}"
            export PROJECT_SSH_CLONE="git@github.com:Icaro-Davi/${{ github.event.repository.name }}.git"
            export PROJECT_ENVS="${{ secrets.PROJECT_ENVS }}"
            sudo bash ~/PROJECTS/BASH/install-dependencies.bash && bash ~/PROJECTS/BASH/get-project-from-git.bash
